const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('sened', {
  loadData: () => ipcRenderer.invoke('data:load'),
  saveData: (data) => ipcRenderer.invoke('data:save', data),
  askAI: (text, history) => ipcRenderer.invoke('ai:ask', { text, history }),
  checkAI: () => ipcRenderer.invoke('ai:check'),
  tgStart: (id, token) => ipcRenderer.invoke('tg:start', { id, token }),
  tgStop: (id) => ipcRenderer.invoke('tg:stop', { id }),
  print: () => ipcRenderer.invoke('app:print'),
  exportPdf: (suggestedName) => ipcRenderer.invoke('app:exportPdf', suggestedName),
  openExternal: (url) => ipcRenderer.invoke('app:openExternal', url),
  openBackupsFolder: () => ipcRenderer.invoke('app:openBackupsFolder'),
  onTgStatus: (cb) => ipcRenderer.on('tg-status', (e, s) => cb(s)),
  onAiChunk: (cb) => ipcRenderer.on('ai:chunk', (e, delta) => cb(delta)),
  onAiReset: (cb) => ipcRenderer.on('ai:reset', () => cb()),
  authVerify: (username, password) => ipcRenderer.invoke('auth:verify', { username, password }),
  authSetCredentials: (username, password) => ipcRenderer.invoke('auth:setCredentials', { username, password }),
  authHashPassword: (password) => ipcRenderer.invoke('auth:hashPassword', password),
  licenseCheckNow: () => ipcRenderer.invoke('license:checkNow'),
  licenseRegenClaimCode: () => ipcRenderer.invoke('license:regenClaimCode'),
  licenseCreateGist: (token) => ipcRenderer.invoke('license:createGist', token),
  onLicenseStatus: (cb) => ipcRenderer.on('license:status', (e, s) => cb(s)),
  aiSetBuiltinKey: (cfg) => ipcRenderer.invoke('ai:setBuiltinKey', cfg),
  aiBuiltinInfo: () => ipcRenderer.invoke('ai:builtinInfo'),
  activationStatus: () => ipcRenderer.invoke('activation:status'),
  activationVerify: (code) => ipcRenderer.invoke('activation:verify', code),
  activationSetDevCode: (code) => ipcRenderer.invoke('activation:setDevCode', code),
  activationHasDevCode: () => ipcRenderer.invoke('activation:hasDevCode'),
  appFlavor: () => ipcRenderer.invoke('app:flavor'),
  appSetFlavor: (flavor) => ipcRenderer.invoke('app:setFlavor', flavor),
  cashierIp: () => ipcRenderer.invoke('app:cashierIp'),
  onSyncUpdated: (cb) => ipcRenderer.on('sync:updated', () => cb()),
  deviceRoleGet: () => ipcRenderer.invoke('deviceRole:get'),
  deviceRoleSet: (role) => ipcRenderer.invoke('deviceRole:set', role),
  deviceRoleClear: () => ipcRenderer.invoke('deviceRole:clear'),
  lanGetConfig: () => ipcRenderer.invoke('lan:getConfig'),
  lanSetConfig: (cfg) => ipcRenderer.invoke('lan:setConfig', cfg),
  lanStatus: () => ipcRenderer.invoke('lan:status'),
  lanTest: (ip, port, token) => ipcRenderer.invoke('lan:test', { ip, port, token })
});
